dropout: 0.0
embedding_dim: 512
extractor_model: openai/clip-vit-base-patch32
extractor_type: clip
freeze_extractors: true
hidden_dim: 768
learning_rate: 0.0001
nhead: 8
num_denoising_steps: 4
num_encoder_layers: 2
scale_factor: 0.1
temperature: 0.07
use_residual: false
weight_decay: 1.0e-05
