# -*- coding: utf-8 -*-
"""create_ilias_webdataset_and_compute_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ksvXY2WFB5-YVO78P8-qCkhPjL_6lfY9
"""

import os
from pathlib import Path
import webdataset as wds
from typing import List, Sequence, Tuple
import torch
import webdataset as wds
from torch.utils.data import DataLoader
from PIL import Image

from feature_extractors import FeatureExtractorFactory

device = "cuda" # change this to your device (e.g., CUDA)
BATCH_SIZE = 64
NUM_WORKERS = 0

ilias_dataset_root = './ilias/' # change this to wherever it's local on your computer
ilias_core_path = Path(ilias_dataset_root) / "ilias_core"
ilias_web_dataset_out = Path(ilias_dataset_root) / "ilias_pairs.tar"

model_name = 'openai/clip-vit-base-patch16'
stem = model_name.replace("/", "-")

out_dir = Path(ilias_dataset_root) / f"ilias_embeds_{stem}"
out_dir.mkdir(parents=True, exist_ok=True)

feature_extractor = FeatureExtractorFactory.create_extractor(
                        model_name=model_name,
                        device=device
                    )
feature_extractor = torch.compile(feature_extractor)

IMG_EXTS = {".jpg", ".jpeg", ".png", ".JPG", ".JPEG", ".PNG"}

def _first_image(p: Path):
    for ext in sorted(IMG_EXTS):
        matches = sorted(p.glob(f"*{ext}"))
        if matches:
            return matches[0]
    matches = [f for f in p.iterdir() if f.suffix.lower() in IMG_EXTS]
    return sorted(matches)[0] if matches else None

def _all_images(p: Path):
    files = []
    for ext in IMG_EXTS:
        files.extend(p.glob(f"*{ext}"))
    return sorted(set(files))

def make_ilias_webdataset(root_dir, output_tar):
    """
    Create a *flat* WebDataset tar:
      - ONE sample for the class query image (role='query')
      - ONE sample per positive image (role='pos')

    Each sample has:
      - 'jpg'      : image bytes
      - 'role.txt' : b'query' or b'pos'
      - 'cls.txt'  : class name (utf-8)
      - 'name.txt' : original filename (utf-8)
    """
    root = Path(root_dir)
    outp = Path(output_tar)
    assert root.exists(), f"Root not found: {root}"

    classes = [d for d in sorted(root.iterdir()) if d.is_dir()]
    sample_idx = 0
    total = 0

    with wds.TarWriter(str(outp)) as sink:
        for cdir in classes:
            cls_name = cdir.name
            qdir = cdir / "query"
            pdir = cdir / "pos"
            if not qdir.exists() or not pdir.exists():
                continue

            # write exactly one query sample
            qimg = _first_image(qdir)
            if qimg:
                sink.write({
                    "__key__": f"{cls_name}/query",  # stable key
                    "jpg": qimg.read_bytes(),
                    "role.txt": b"query",
                    "cls.txt": cls_name.encode("utf-8"),
                    "name.txt": qimg.name.encode("utf-8"),
                })
                sample_idx += 1
                total += 1

            # write all positives as separate samples
            for pos_path in _all_images(pdir):
                sink.write({
                    "__key__": f"{cls_name}/pos/{pos_path.stem}",
                    "jpg": pos_path.read_bytes(),
                    "role.txt": b"pos",
                    "cls.txt": cls_name.encode("utf-8"),
                    "name.txt": pos_path.name.encode("utf-8"),
                })
                sample_idx += 1
                total += 1

    print(f"Wrote {total} flat samples from {len(classes)} classes to {outp}")

make_ilias_webdataset(
    ilias_core_path,
    ilias_web_dataset_out
)

def build_ilias_flat_dataset(shard_dir: str | Path):
    shard_dir = Path(shard_dir)
    shards = sorted(str(shard_dir / f) for f in os.listdir(shard_dir) if f.endswith(".tar"))

    ds = (
        wds.WebDataset(shards, repeat=False)
        # keep only samples that actually have an image under "jpg"
        .select(lambda s: ("__key__" in s) and ("jpg" in s))
        .decode("pil")
        .to_tuple("__key__", "jpg")                 # -> (key, PIL.Image)
        .map_tuple(lambda k: k, lambda im: im.convert("RGB"))
    )
    return ds

# -------------------- DATALOADER -------------------- #
def collate_pil(samples: Sequence[Tuple[str, Image.Image]]):
    keys, imgs = zip(*samples)
    return list(keys), list(imgs)

# choose the right builder:
dataset = build_ilias_flat_dataset(ilias_dataset_root)

loader = DataLoader(
    dataset,
    batch_size=BATCH_SIZE,
    num_workers=NUM_WORKERS,
    pin_memory=True,
    collate_fn=collate_pil,
)

# -------------------- EXTRACTION LOOP (unchanged) -------------------- #
def save_chunk(out_dir: Path, stem: str, idx: int,
               keys: List[str], tensors: List[torch.Tensor],
               dtype: torch.dtype) -> None:
    path = out_dir / f"{stem}_{idx:04d}.pt"
    torch.save({"keys": keys, "embeddings": torch.cat(tensors).to(dtype)}, path)
    print(f"Saved {path.name}  ({len(keys):,} embeddings)")


emb_buf, key_buf = [], []
target_dtype = torch.float16

for i, (keys, imgs) in enumerate(loader):
    if (i % 10) == 0:
        print(i)
    with torch.no_grad():
        embs = feature_extractor.extract_image_features(imgs)  # expects list[PIL]
    emb_buf.append(embs.cpu())
    key_buf.extend(keys)

save_chunk(out_dir, stem, 0, key_buf, emb_buf, target_dtype)